name: build
on:
  push:
    branches:
      - main
      - fork
  pull_request:

jobs:
  golangci:
    name: CI
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go-version: [ oldstable, stable ]
        # windows is ignored because some tests are based on filepath.
        os: [ubuntu-latest, macos-latest]
    env:
      GOLANGCI_LINT_VERSION: v2.11
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: oldstable
      - uses: golangci/golangci-lint-action@v9
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}
          install-only: true
      - run: make lint
      - run: make test
      - run: make build
